#!/usr/bin/env bash
# ============================================================================
# setup-ghostty-defaults.sh — make Ghostty the default terminal on
# Ubuntu 24.04 / GNOME 46.
#
#   1. Registers the Ghostty binary as the x-terminal-emulator alternative
#      (priority 50) and selects it as the default.
#   2. Clears GNOME's built-in Ctrl+Alt+T (GNOME Terminal) binding and adds
#      a custom shortcut: Ctrl+Alt+T -> ghostty.
#   3. Sets the legacy org.gnome.desktop.default-applications.terminal keys
#      (deprecated in GNOME, but still read by some tools).
#   4. Symlinks ~/.config/ghostty/config -> ./ghostty/config
#
# Idempotent — safe to re-run after reinstalls or distro upgrades.
# The two root commands go through pkexec: approve the GUI polkit prompt.
# ============================================================================
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GHOSTTY_BIN="$(command -v ghostty || true)"
GHOSTTY_BIN="${GHOSTTY_BIN:-/usr/bin/ghostty}"
KB_ROOT="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
BINDING='<Control><Alt>t'

echo "==> Ghostty binary: $GHOSTTY_BIN"
[ -x "$GHOSTTY_BIN" ] || { echo "ERROR: $GHOSTTY_BIN not found or not executable" >&2; exit 1; }

# --- Step 1: x-terminal-emulator alternative (root) --------------------------
echo "==> Registering $GHOSTTY_BIN as x-terminal-emulator (priority 50)..."
pkexec update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator "$GHOSTTY_BIN" 50
pkexec update-alternatives --set x-terminal-emulator "$GHOSTTY_BIN"

# --- Step 2: Ctrl+Alt+T -> Ghostty (no root) ---------------------------------
echo "==> Clearing built-in 'Launch terminal' binding (GNOME Terminal)..."
gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '@as []'

# Pick the first free customN slot so existing custom shortcuts are never clobbered.
slot=""
for i in $(seq 0 20); do
    candidate="${KB_ROOT}/custom${i}/"
    if ! gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings | grep -qF "$candidate"; then
        slot="custom${i}"
        break
    fi
done
[ -n "$slot" ] || { echo "ERROR: no free custom-keybinding slot" >&2; exit 1; }

echo "==> Adding custom shortcut ($slot): $BINDING -> ghostty"
python3 - "$KB_ROOT" "$slot" "$BINDING" <<'EOF'
import subprocess, sys

kb_root, slot, binding = sys.argv[1], sys.argv[2], sys.argv[3]
SCHEMA = 'org.gnome.settings-daemon.plugins.media-keys'
path = f"{kb_root}/{slot}/"

cur = subprocess.check_output(
    ['gsettings', 'get', SCHEMA, 'custom-keybindings'], text=True
).strip()
items = [] if cur == '@as []' else [x.strip().strip("'") for x in cur[1:-1].split(',')]
if path not in items:
    items.append(path)

new_list = '[' + ','.join(f"'{x}'" for x in items) + ']'
subprocess.check_call(['gsettings', 'set', SCHEMA, 'custom-keybindings', new_list])

for key, val in (('name', 'Ghostty'), ('command', 'ghostty'), ('binding', binding)):
    subprocess.check_call([
        'gsettings', 'set', f'{SCHEMA}.custom-keybinding:{path}', key, val
    ])
EOF

# --- Step 3: legacy default-applications keys (no root) ----------------------
echo "==> Setting org.gnome.desktop.default-applications.terminal -> ghostty"
gsettings set org.gnome.desktop.default-applications.terminal exec 'ghostty'
gsettings set org.gnome.desktop.default-applications.terminal exec-arg '-e'

# --- Ghostty config symlink ---------------------------------------------------
echo "==> Linking ~/.config/ghostty/config -> $DOTFILES_DIR/ghostty/config"
mkdir -p "$HOME/.config/ghostty"
ln -sfn "$DOTFILES_DIR/ghostty/config" "$HOME/.config/ghostty/config"
rm -f "$HOME/.config/ghostty/config.ghostty"   # stale 0-byte autogenerated file

# --- Verification -------------------------------------------------------------
echo
echo "==> Result:"
update-alternatives --query x-terminal-emulator | grep -E '^(Status|Best|Value):'
gsettings get org.gnome.settings-daemon.plugins.media-keys terminal
gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings
gsettings get org.gnome.desktop.default-applications.terminal exec
echo
echo "==> Done. Ctrl+Alt+T now opens Ghostty."
echo "    NOTE: Nautilus 'Open in Terminal' on Ubuntu 24.04 is hardcoded to GNOME Terminal"
echo "    (nautilus-extension-gnome-terminal) and ignores x-terminal-emulator; install"
echo "    nautilus-open-any-terminal for that menu to launch Ghostty."
